### ISSUE TITLE
Modular AI plugins

### ISSUE THREAD

**Issue by artifishvr** [spongedsc/SpongeChat#53]
With the frequency that we've changed AI providers, I think having the ability to quickly swap between or write new integrations would be useful

**Comment by daniwasonline** [comment]
UPDATE: We've made some significant progress with this in #55! The Workers AI "mini-SDK" implemented (see https://github.com/spongedsc/SpongeChat/blob/v2/src/util/models/index.js) will likely be the model for implementing future providers in plugins.

### To-do

- [x] Create model mini-SDK
- [ ] Fully standardise model API
- [ ] Implement a secondary provider (OpenAI?)
